<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Modules Path
    |--------------------------------------------------------------------------
    |
    | Directory where Bounded Contexts (modules) live. Mirrors the nwidart
    | convention by default. Override here if you keep modules elsewhere.
    |
    */

    'modules_path' => base_path('Modules'),

    /*
    |--------------------------------------------------------------------------
    | Default Mode
    |--------------------------------------------------------------------------
    |
    | 'pragmatic' — Eloquent Model used as the rich entity (Spatie style).
    |               Domain/Entities, Domain/ValueObjects and Domain/Repositories
    |               are NOT generated by arch:make-module.
    |
    | 'purist'    — Pure PHP entities + Repository pattern. Full DDD folder
    |               layout is generated. Boundary rule R4 (Application cannot
    |               import Infrastructure) is enforced.
    |
    */

    'default_mode' => env('MODULES_ARCH_MODE', 'pragmatic'),

    /*
    |--------------------------------------------------------------------------
    | Boundary Enforcement
    |--------------------------------------------------------------------------
    |
    | Configuration for `php artisan arch:check-boundaries`. Toggle individual
    | rules below. R4 is OFF by default in pragmatic mode and ON in purist.
    |
    */

    'boundaries' => [
        'enabled' => true,

        'rules' => [
            'cross_module_via_contracts' => true,  // R1
            'domain_no_infrastructure' => true,  // R2
            'domain_no_application' => true,  // R3
            'application_no_infrastructure' => false, // R4 (purist only)
            'declared_subscriptions' => true,  // R5
            'aggregate_root_repositories' => true,  // R6 (warning, not error)
        ],

        'ignored_namespaces' => [
            'Illuminate\\Support\\',
            'Illuminate\\Contracts\\',
        ],
    ],
];
